var data = [
 {
   "designID": 11,
   "MapName": "ARROWEYE FULFILLMENT FLOW",
   "id": 2265,
   "xPlot": 4,
   "yPlot": 5,
   "flowHeader": "Ready to Pick",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "6,5",
   "BAEendpoint": "8,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/2",
   "description": "STABLE: Less than 0.5% of shipments in Ready to Pick status for longer than 30.0 mins."
 },
 {
   "designID": 11,
   "MapName": "ARROWEYE FULFILLMENT FLOW",
   "id": 2266,
   "xPlot": 8,
   "yPlot": 5,
   "flowHeader": "FCS Integrated",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "10,5",
   "BAEendpoint": "12,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/14",
   "description": "STABLE: Less than 0.5% of shipments in Integrated to FCS status for longer than 2.0 hours."
 },
 {
   "designID": 11,
   "MapName": "ARROWEYE FULFILLMENT FLOW",
   "id": 2268,
   "xPlot": 12,
   "yPlot": 5,
   "flowHeader": "FIL to Arroweye",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "14,5",
   "BAEendpoint": "16,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/30",
   "description": "STABLE: Less than 0.5% of shipments in FIL Pushed to Arroweye status for longer than 2.0 hours."
 },
 {
   "designID": 11,
   "MapName": "ARROWEYE FULFILLMENT FLOW",
   "id": 2269,
   "xPlot": 16,
   "yPlot": 5,
   "flowHeader": "Acknowledged",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "red",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "18,5",
   "BAEendpoint": "20,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "418/418",
   "description": "CRITICAL: More than 0.75% of shipments in Arroweye Acknowledged status for longer than 2.0 hours."
 },
 {
   "designID": 11,
   "MapName": "ARROWEYE FULFILLMENT FLOW",
   "id": 2270,
   "xPlot": 20,
   "yPlot": 5,
   "flowHeader": "Ship Confirmed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "22,5",
   "BAEendpoint": "24,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/122",
   "description": "STABLE: Less than 0.5% of shipments in Shipment Confirmed by Arroweye status for longer than 2.0 days."
 },
 {
   "designID": 11,
   "MapName": "ARROWEYE FULFILLMENT FLOW",
   "id": 2273,
   "xPlot": 24,
   "yPlot": 5,
   "flowHeader": "Ship Closed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "24,5",
   "BAEendpoint": "24,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 1,
   "MapName": "D2C",
   "id": 1,
   "xPlot": 1,
   "yPlot": 4,
   "flowHeader": "Product\\nAvailibility",
   "flowURL": null,
   "seqID": 0,
   "flowStatus": "green",
   "stationType": "interchange-rsign",
   "seqEND": 0,
   "lineDirection": "",
   "textDirection": null,
   "BAEmidpoint": "2,4",
   "BAEendpoint": "3,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 1,
   "MapName": "D2C",
   "id": 3,
   "xPlot": 3,
   "yPlot": 4,
   "flowHeader": "E-COM",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#614051",
   "stationType": "interchange-yellow",
   "seqEND": 1,
   "lineDirection": "",
   "textDirection": null,
   "BAEmidpoint": "4,4",
   "BAEendpoint": "5,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 1,
   "MapName": "D2C",
   "id": 4,
   "xPlot": 5,
   "yPlot": 4,
   "flowHeader": "Place Holder",
   "flowURL": null,
   "seqID": 3,
   "flowStatus": "yellow",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "",
   "textDirection": null,
   "BAEmidpoint": "6,3",
   "BAEendpoint": "8,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 1,
   "MapName": "D2C",
   "id": 7,
   "xPlot": 8,
   "yPlot": 2,
   "flowHeader": "Order\\nManagment",
   "flowURL": null,
   "seqID": 4,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "",
   "textDirection": null,
   "BAEmidpoint": "6.5,2",
   "BAEendpoint": "5,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 1,
   "MapName": "D2C",
   "id": 10,
   "xPlot": 5,
   "yPlot": 2,
   "flowHeader": "POOL Fill",
   "flowURL": null,
   "seqID": 7,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "",
   "textDirection": null,
   "BAEmidpoint": "2.5,2",
   "BAEendpoint": "3,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 1,
   "MapName": "D2C",
   "id": 11,
   "xPlot": 2,
   "yPlot": 2,
   "flowHeader": "Store Fill",
   "flowURL": null,
   "seqID": 8,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "W",
   "textDirection": null,
   "BAEmidpoint": "3.2,2",
   "BAEendpoint": "2,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 3,
   "MapName": "D2C Orders",
   "id": 16,
   "xPlot": 2,
   "yPlot": 5,
   "flowHeader": "Prdct Availibilty",
   "flowURL": null,
   "seqID": 0,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "4,5",
   "BAEendpoint": "6,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 3,
   "MapName": "D2C Orders",
   "id": 17,
   "xPlot": 6,
   "yPlot": 5,
   "flowHeader": "Order Captures",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "8,5",
   "BAEendpoint": "10,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 3,
   "MapName": "D2C Orders",
   "id": 18,
   "xPlot": 10,
   "yPlot": 5,
   "flowHeader": "Order Mngmt",
   "flowURL": null,
   "seqID": 2,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "12,5",
   "BAEendpoint": "14,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 3,
   "MapName": "D2C Orders",
   "id": 19,
   "xPlot": 14,
   "yPlot": 5,
   "flowHeader": "Order Fulfillment",
   "flowURL": null,
   "seqID": 3,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "16,5",
   "BAEendpoint": "18,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 3,
   "MapName": "D2C Orders",
   "id": 20,
   "xPlot": 18,
   "yPlot": 5,
   "flowHeader": "Ship Confirmation",
   "flowURL": null,
   "seqID": 4,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "20,5",
   "BAEendpoint": "22,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 3,
   "MapName": "D2C Orders",
   "id": 21,
   "xPlot": 22,
   "yPlot": 5,
   "flowHeader": "Order Closed",
   "flowURL": null,
   "seqID": 5,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": null,
   "BAEendpoint": null,
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 10,
   "MapName": "DROPSHIP FULFILLMENT FLOW",
   "id": 2252,
   "xPlot": 2,
   "yPlot": 5,
   "flowHeader": "Ready to Pick",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "3.5,5",
   "BAEendpoint": "5,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/537",
   "description": "STABLE: Less than 0.5% of shipments in Ready to Pick status for longer than 6.0 hours."
 },
 {
   "designID": 10,
   "MapName": "DROPSHIP FULFILLMENT FLOW",
   "id": 2253,
   "xPlot": 5,
   "yPlot": 5,
   "flowHeader": "PO Generated",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "6.5,5",
   "BAEendpoint": "8,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "6/737",
   "description": "STABLE: Less than 0.5% of shipments in PO Number Generated in FIL status for longer than 2.0 hours."
 },
 {
   "designID": 10,
   "MapName": "DROPSHIP FULFILLMENT FLOW",
   "id": 2254,
   "xPlot": 8,
   "yPlot": 5,
   "flowHeader": "PO Sent to Vendor",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "9.5,5",
   "BAEendpoint": "11,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "1738/5971",
   "description": "STABLE: Less than 0.5% of shipments in PO Sent to Vendor (FedBuy) status for longer than 24.0 hours."
 },
 {
   "designID": 10,
   "MapName": "DROPSHIP FULFILLMENT FLOW",
   "id": 2255,
   "xPlot": 11,
   "yPlot": 5,
   "flowHeader": "Vendor Acknowledged",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "red",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "12.5,5",
   "BAEendpoint": "14,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "5047/5502",
   "description": "CRITICAL: More than 0.75% of shipments in Vendor Acknowledged to FIL status for longer than 2.0 hours."
 },
 {
   "designID": 10,
   "MapName": "DROPSHIP FULFILLMENT FLOW",
   "id": 2256,
   "xPlot": 14,
   "yPlot": 5,
   "flowHeader": "Ship Confirmed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "15.5,5",
   "BAEendpoint": "17,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/2",
   "description": "STABLE: Less than 0.5% of shipments in Shipment Confirmed status for longer than 60.0 mins."
 },
 {
   "designID": 10,
   "MapName": "DROPSHIP FULFILLMENT FLOW",
   "id": 2259,
   "xPlot": 17,
   "yPlot": 5,
   "flowHeader": "Ship Closed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "18.5,5",
   "BAEendpoint": "20,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "741/30250",
   "description": "STABLE: Less than 1.0% of shipments in Confirmed-Item on Order status for longer than 91.3 days."
 },
 {
   "designID": 10,
   "MapName": "DROPSHIP FULFILLMENT FLOW",
   "id": 2260,
   "xPlot": 20,
   "yPlot": 5,
   "flowHeader": "PO Closed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "20,5",
   "BAEendpoint": "20,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 12,
   "MapName": "EGC FULFILLMENT FLOW",
   "id": 2274,
   "xPlot": 4,
   "yPlot": 5,
   "flowHeader": "Ready to Pick",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "6,5",
   "BAEendpoint": "8,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "6-Jan",
   "description": "STABLE: Less than 0.5% of shipments in Ready to Pick status for longer than 30.0 mins."
 },
 {
   "designID": 12,
   "MapName": "EGC FULFILLMENT FLOW",
   "id": 2275,
   "xPlot": 8,
   "yPlot": 5,
   "flowHeader": "FCS Integrated",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "red",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "10,5",
   "BAEendpoint": "12,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "72/72",
   "description": "CRITICAL: More than 0.75% of shipments in Integrated to FCS status for longer than 2.0 hours."
 },
 {
   "designID": 12,
   "MapName": "EGC FULFILLMENT FLOW",
   "id": 2276,
   "xPlot": 12,
   "yPlot": 5,
   "flowHeader": "FCS to FIL",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "14,5",
   "BAEendpoint": "16,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 12,
   "MapName": "EGC FULFILLMENT FLOW",
   "id": 2277,
   "xPlot": 16,
   "yPlot": 5,
   "flowHeader": "Store",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "18,5",
   "BAEendpoint": "20,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 12,
   "MapName": "EGC FULFILLMENT FLOW",
   "id": 2278,
   "xPlot": 20,
   "yPlot": 5,
   "flowHeader": "Ship Confirmed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "22,5",
   "BAEendpoint": "24,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/2",
   "description": "STABLE: Less than 0.5% of shipments in Shipment Confirmed status for longer than 2.0 days."
 },
 {
   "designID": 12,
   "MapName": "EGC FULFILLMENT FLOW",
   "id": 2279,
   "xPlot": 24,
   "yPlot": 5,
   "flowHeader": "Ship Closed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "24,5",
   "BAEendpoint": "24,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "19/1017",
   "description": "STABLE: Less than 1.0% of shipments in Shipment Closed status for longer than 91.3 days."
 },
 {
   "designID": 2,
   "MapName": "FIL",
   "id": 5,
   "xPlot": 1,
   "yPlot": 3,
   "flowHeader": "FedFil",
   "flowURL": null,
   "seqID": 0,
   "flowStatus": "red",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "",
   "textDirection": null,
   "BAEmidpoint": null,
   "BAEendpoint": null,
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 2,
   "MapName": "FIL",
   "id": 6,
   "xPlot": 3,
   "yPlot": 2,
   "flowHeader": "Portland",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "",
   "textDirection": null,
   "BAEmidpoint": null,
   "BAEendpoint": null,
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 880,
   "xPlot": 1,
   "yPlot": 1,
   "flowHeader": "Credit",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "2.5,1",
   "BAEendpoint": "4,1",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 881,
   "xPlot": 4,
   "yPlot": 1,
   "flowHeader": "STGMSTRMISS",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "5.5,1",
   "BAEendpoint": "7,1",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 882,
   "xPlot": 7,
   "yPlot": 1,
   "flowHeader": "STGMSTRWAIT",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "8.5,1",
   "BAEendpoint": "10,1",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 883,
   "xPlot": 10,
   "yPlot": 1,
   "flowHeader": "STGMSTRREADY",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "11.5,1",
   "BAEendpoint": "13,1",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 884,
   "xPlot": 13,
   "yPlot": 1,
   "flowHeader": "STGMSTRFAIL",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "14.5,1",
   "BAEendpoint": "16,1",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 885,
   "xPlot": 16,
   "yPlot": 1,
   "flowHeader": "STGMSTRFAIL2",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "17.5,1",
   "BAEendpoint": "19,1",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 886,
   "xPlot": 19,
   "yPlot": 1,
   "flowHeader": "STG2CORE-1",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "E",
   "BAEmidpoint": "19,2",
   "BAEendpoint": "19,3",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 887,
   "xPlot": 19,
   "yPlot": 14,
   "flowHeader": "CHESHIRE/ALTFIL",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "W",
   "BAEmidpoint": "28,14",
   "BAEendpoint": "28,14",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 888,
   "xPlot": 19,
   "yPlot": 3,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "19,3",
   "BAEendpoint": "19,14",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 889,
   "xPlot": 19,
   "yPlot": 4,
   "flowHeader": "STORES/CONNSHIP",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "W",
   "BAEmidpoint": "20.5,4",
   "BAEendpoint": "22,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 890,
   "xPlot": 22,
   "yPlot": 4,
   "flowHeader": "STORES/SHPCONF",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "S",
   "BAEmidpoint": "23.5,4",
   "BAEendpoint": "28,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 891,
   "xPlot": 19,
   "yPlot": 6,
   "flowHeader": "EEC/GETEECNBR",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "W",
   "BAEmidpoint": "20.5,6",
   "BAEendpoint": "22,6",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 892,
   "xPlot": 22,
   "yPlot": 6,
   "flowHeader": "EEC/EGCRECV_EEC",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "S",
   "BAEmidpoint": "23.5,6",
   "BAEendpoint": "28,6",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 893,
   "xPlot": 19,
   "yPlot": 8,
   "flowHeader": "EGC/\\nGETEGCNBR",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "W",
   "BAEmidpoint": "20.5,8",
   "BAEendpoint": "22,8",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 894,
   "xPlot": 21,
   "yPlot": 8,
   "flowHeader": "EGC/AE-ACK",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "S",
   "BAEmidpoint": "22.5,8",
   "BAEendpoint": "23,8",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 895,
   "xPlot": 23,
   "yPlot": 8,
   "flowHeader": "BLMEGC/\\nEGCRECV-BLM",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "S",
   "BAEmidpoint": "24.5,8",
   "BAEendpoint": "25,8",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 896,
   "xPlot": 25,
   "yPlot": 8,
   "flowHeader": "EGC/AE-SHIP",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "S",
   "BAEmidpoint": "27.5,8",
   "BAEendpoint": "28,8",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 897,
   "xPlot": 19,
   "yPlot": 10,
   "flowHeader": "VGC",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "W",
   "BAEmidpoint": "21,10",
   "BAEendpoint": "28,10",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 898,
   "xPlot": 19,
   "yPlot": 12,
   "flowHeader": "WMS/\\nWMSINTEGRATE",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "W",
   "BAEmidpoint": "20.5,12",
   "BAEendpoint": "22,12",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 899,
   "xPlot": 22,
   "yPlot": 12,
   "flowHeader": "WMS/\\nSHPCONF",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "23.5,12",
   "BAEendpoint": "28.1,12",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 900,
   "xPlot": 28,
   "yPlot": 1,
   "flowHeader": "OES-Email",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "E",
   "BAEmidpoint": "28,3",
   "BAEendpoint": "28,1",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 8,
   "MapName": "FILHealthCheck",
   "id": 901,
   "xPlot": 28,
   "yPlot": 3,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "28,3",
   "BAEendpoint": "28,14.12",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 7,
   "MapName": "FILTest",
   "id": 134,
   "xPlot": 1,
   "yPlot": 4,
   "flowHeader": "Point 1",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "2,4",
   "BAEendpoint": "3,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 7,
   "MapName": "FILTest",
   "id": 135,
   "xPlot": 3,
   "yPlot": 4,
   "flowHeader": "Point 2",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "red",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "4,4",
   "BAEendpoint": "5,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 7,
   "MapName": "FILTest",
   "id": 136,
   "xPlot": 5,
   "yPlot": 4,
   "flowHeader": "Point 3",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "6,4",
   "BAEendpoint": "7,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 7,
   "MapName": "FILTest",
   "id": 137,
   "xPlot": 7,
   "yPlot": 4,
   "flowHeader": "Point 4",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "8,4",
   "BAEendpoint": "9,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 7,
   "MapName": "FILTest",
   "id": 138,
   "xPlot": 9,
   "yPlot": 4,
   "flowHeader": "Point 5",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "10,4",
   "BAEendpoint": "11,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 7,
   "MapName": "FILTest",
   "id": 139,
   "xPlot": 11,
   "yPlot": 4,
   "flowHeader": "Point 6",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "yellow",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "12,4",
   "BAEendpoint": "13,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 7,
   "MapName": "FILTest",
   "id": 140,
   "xPlot": 13,
   "yPlot": 4,
   "flowHeader": "Point 7",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "red",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "14,4",
   "BAEendpoint": "15,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 7,
   "MapName": "FILTest",
   "id": 141,
   "xPlot": 15,
   "yPlot": 4,
   "flowHeader": "Point 8",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "16,4",
   "BAEendpoint": "17,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 7,
   "MapName": "FILTest",
   "id": 142,
   "xPlot": 17,
   "yPlot": 4,
   "flowHeader": "Point 9",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": null,
   "BAEendpoint": "19,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 7,
   "MapName": "FILTest",
   "id": 143,
   "xPlot": 19,
   "yPlot": 4,
   "flowHeader": "Point 10",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": null,
   "BAEendpoint": "19,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 7,
   "MapName": "FILTest",
   "id": 145,
   "xPlot": 19,
   "yPlot": 4,
   "flowHeader": "Point 1",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "19,6",
   "BAEendpoint": "19,8",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 14,
   "MapName": "JOPPA FULFILLMENT FLOW",
   "id": 2287,
   "xPlot": 4,
   "yPlot": 5,
   "flowHeader": "Ready to Pick",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "red",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "6,5",
   "BAEendpoint": "8,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "467/611",
   "description": "CRITICAL: More than 0.75% of shipments in Ready to Pick status for longer than 30.0 mins."
 },
 {
   "designID": 14,
   "MapName": "JOPPA FULFILLMENT FLOW",
   "id": 2288,
   "xPlot": 8,
   "yPlot": 5,
   "flowHeader": "Ready to Fill",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "10,5",
   "BAEendpoint": "12,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 14,
   "MapName": "JOPPA FULFILLMENT FLOW",
   "id": 2289,
   "xPlot": 12,
   "yPlot": 5,
   "flowHeader": "Invoice Printed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "14,5",
   "BAEendpoint": "16,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "253/1387",
   "description": "STABLE: Less than 0.5% of shipments in Invoice Printed  status for longer than 6.0 hours."
 },
 {
   "designID": 14,
   "MapName": "JOPPA FULFILLMENT FLOW",
   "id": 2290,
   "xPlot": 16,
   "yPlot": 5,
   "flowHeader": "Ship Confirmed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "18,5",
   "BAEendpoint": "20,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/33",
   "description": "STABLE: Less than 0.5% of shipments in Shipment Confirmed status for longer than 2.0 days."
 },
 {
   "designID": 14,
   "MapName": "JOPPA FULFILLMENT FLOW",
   "id": 2291,
   "xPlot": 20,
   "yPlot": 5,
   "flowHeader": "Ship Closed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "20,5",
   "BAEendpoint": "20,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "169/3037",
   "description": "STABLE: Less than 1.0% of shipments in Shipment Closed status for longer than 24.0 hours."
 },
 {
   "designID": 5,
   "MapName": "OF/SC",
   "id": 31,
   "xPlot": 2,
   "yPlot": 2,
   "flowHeader": "OF",
   "flowURL": null,
   "seqID": 0,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "13,2",
   "BAEendpoint": "21,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 5,
   "MapName": "OF/SC",
   "id": 32,
   "xPlot": 21,
   "yPlot": 2,
   "flowHeader": "SC",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": null,
   "BAEendpoint": null,
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 5,
   "MapName": "OF/SC",
   "id": 33,
   "xPlot": 2,
   "yPlot": 2,
   "flowHeader": "STR",
   "flowURL": null,
   "seqID": 2,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "11,1",
   "BAEendpoint": "21,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 5,
   "MapName": "OF/SC",
   "id": 34,
   "xPlot": 2,
   "yPlot": 2,
   "flowHeader": "WMS",
   "flowURL": null,
   "seqID": 3,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "4,5",
   "BAEendpoint": "5,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 5,
   "MapName": "OF/SC",
   "id": 35,
   "xPlot": 5,
   "yPlot": 5,
   "flowHeader": "PD",
   "flowURL": null,
   "seqID": 4,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "11,3",
   "BAEendpoint": "21,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 5,
   "MapName": "OF/SC",
   "id": 36,
   "xPlot": 5,
   "yPlot": 5,
   "flowHeader": "GY",
   "flowURL": null,
   "seqID": 5,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "11,4",
   "BAEendpoint": "21,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 5,
   "MapName": "OF/SC",
   "id": 37,
   "xPlot": 5,
   "yPlot": 5,
   "flowHeader": "CH",
   "flowURL": null,
   "seqID": 6,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "11,5",
   "BAEendpoint": "21,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 5,
   "MapName": "OF/SC",
   "id": 38,
   "xPlot": 5,
   "yPlot": 5,
   "flowHeader": "SN",
   "flowURL": null,
   "seqID": 5,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "11,6",
   "BAEendpoint": "21,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 5,
   "MapName": "OF/SC",
   "id": 39,
   "xPlot": 5,
   "yPlot": 5,
   "flowHeader": "OK",
   "flowURL": null,
   "seqID": 6,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "11,7",
   "BAEendpoint": "21,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 5,
   "MapName": "OF/SC",
   "id": 40,
   "xPlot": 5,
   "yPlot": 5,
   "flowHeader": "WV",
   "flowURL": null,
   "seqID": 7,
   "flowStatus": "red",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "11,8",
   "BAEendpoint": "21,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 4,
   "MapName": "OM/OF",
   "id": 22,
   "xPlot": 2,
   "yPlot": 3,
   "flowHeader": "OM",
   "flowURL": null,
   "seqID": 0,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "9,3",
   "BAEendpoint": "16,3",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 4,
   "MapName": "OM/OF",
   "id": 23,
   "xPlot": 16,
   "yPlot": 3,
   "flowHeader": "OF",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "19,3",
   "BAEendpoint": "22,3",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 4,
   "MapName": "OM/OF",
   "id": 24,
   "xPlot": 2,
   "yPlot": 3,
   "flowHeader": "OCon",
   "flowURL": null,
   "seqID": 3,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "5,5",
   "BAEendpoint": "7,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 4,
   "MapName": "OM/OF",
   "id": 25,
   "xPlot": 7,
   "yPlot": 5,
   "flowHeader": "StC",
   "flowURL": null,
   "seqID": 4,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "9,5",
   "BAEendpoint": "11,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 4,
   "MapName": "OM/OF",
   "id": 26,
   "xPlot": 11,
   "yPlot": 5,
   "flowHeader": "RP",
   "flowURL": null,
   "seqID": 5,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "13,5",
   "BAEendpoint": "16,3",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 4,
   "MapName": "OM/OF",
   "id": 27,
   "xPlot": 16,
   "yPlot": 3,
   "flowHeader": "STR",
   "flowURL": null,
   "seqID": 6,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "19,5",
   "BAEendpoint": "22,3",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 4,
   "MapName": "OM/OF",
   "id": 28,
   "xPlot": 16,
   "yPlot": 3,
   "flowHeader": "WMS",
   "flowURL": null,
   "seqID": 7,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 1,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "19,8",
   "BAEendpoint": "22,3",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 4,
   "MapName": "OM/OF",
   "id": 30,
   "xPlot": 22,
   "yPlot": 3,
   "flowHeader": "SC",
   "flowURL": null,
   "seqID": 8,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": null,
   "BAEendpoint": null,
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2221,
   "xPlot": 4,
   "yPlot": 18,
   "flowHeader": "Core\\n",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "red",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "5,18",
   "BAEendpoint": "7,18",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "3449/4020",
   "description": "CRITICAL: More than 0.75% of shipments in Staging to Core status for longer than 2.0 hours."
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2222,
   "xPlot": 7,
   "yPlot": 18,
   "flowHeader": "In Process",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "red",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "9,18",
   "BAEendpoint": "12,18",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "916/1016",
   "description": "CRITICAL: More than 0.75% of shipments in Shipment in Process status for longer than 60.0 mins."
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2229,
   "xPlot": 7,
   "yPlot": 18,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "N",
   "textDirection": "E",
   "BAEmidpoint": "7,10",
   "BAEendpoint": "7,0.88",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2230,
   "xPlot": 7,
   "yPlot": 16,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "8,16",
   "BAEendpoint": "9,16",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2231,
   "xPlot": 9,
   "yPlot": 16,
   "flowHeader": "Void-Fraud\\n",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "9,16",
   "BAEendpoint": "9,16",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/1",
   "description": "STABLE: Less than 1.0% of shipments in Void - Fraud status for longer than 2.0 days."
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2232,
   "xPlot": 7,
   "yPlot": 14,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "8,14",
   "BAEendpoint": "9,14",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2233,
   "xPlot": 9,
   "yPlot": 14,
   "flowHeader": "Void-Not Avail\\n",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "9,14",
   "BAEendpoint": "9,14",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/337",
   "description": "STABLE: Less than 1.0% of shipments in Not Available Void status for longer than 91.3 days."
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2234,
   "xPlot": 7,
   "yPlot": 12,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "S",
   "BAEmidpoint": "8,12",
   "BAEendpoint": "9,12",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2235,
   "xPlot": 9,
   "yPlot": 12,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "S",
   "BAEmidpoint": "9,12",
   "BAEendpoint": "9,12",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2236,
   "xPlot": 9,
   "yPlot": 12,
   "flowHeader": "Void-Other\\n",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "9,12",
   "BAEendpoint": "9,12",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/14",
   "description": "STABLE: Less than 1.0% of shipments in Void - Other status for longer than 91.3 days."
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2237,
   "xPlot": 7,
   "yPlot": 10,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "8,10",
   "BAEendpoint": "9,10",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2238,
   "xPlot": 9,
   "yPlot": 10,
   "flowHeader": "Hold-\\nCredit Referred",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "9,11",
   "BAEendpoint": "7.1,11",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "2/235",
   "description": "STABLE: Less than 0.5% of shipments in Hold - Credit Referred   status for longer than 2.0 days."
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2239,
   "xPlot": 7,
   "yPlot": 8,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "8,8",
   "BAEendpoint": "9,8",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2240,
   "xPlot": 9,
   "yPlot": 8,
   "flowHeader": "Void-\\nCust Request",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "9,8",
   "BAEendpoint": "9,8",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2241,
   "xPlot": 7,
   "yPlot": 6,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "8,6",
   "BAEendpoint": "9,6",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2242,
   "xPlot": 9,
   "yPlot": 6,
   "flowHeader": "On Special\\nOrder",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "9,7",
   "BAEendpoint": "7.1,7",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2243,
   "xPlot": 7,
   "yPlot": 4,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "8,4",
   "BAEendpoint": "9,4",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2244,
   "xPlot": 9,
   "yPlot": 4,
   "flowHeader": "On Backorder",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "S",
   "textDirection": "E",
   "BAEmidpoint": "9,5",
   "BAEendpoint": "7.1,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/4319",
   "description": "STABLE: Less than 1.0% of shipments in Confirmed-Item on Order status for longer than 91.3 days."
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2245,
   "xPlot": 7,
   "yPlot": 2,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "",
   "textDirection": "E",
   "BAEmidpoint": "8,2",
   "BAEendpoint": "9,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2246,
   "xPlot": 9,
   "yPlot": 2,
   "flowHeader": "Void-Past Due",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "",
   "textDirection": "E",
   "BAEmidpoint": "9,2",
   "BAEendpoint": "9,2",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/21",
   "description": "STABLE: Less than 1.0% of shipments in Past Due Void status for longer than 91.3 days."
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2247,
   "xPlot": 7,
   "yPlot": 1,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "#d3d3d3",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "",
   "textDirection": "E",
   "BAEmidpoint": "8,1",
   "BAEendpoint": "9,1",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2248,
   "xPlot": 9,
   "yPlot": 1,
   "flowHeader": "Void-Null\\n",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "",
   "textDirection": "E",
   "BAEmidpoint": "9,1",
   "BAEendpoint": "9,1",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/1205",
   "description": "STABLE: Less than 1.0% of shipments in Null Void status for longer than 91.3 days."
 },
 {
   "designID": 9,
   "MapName": "ORDER FULFILLMENT FLOW",
   "id": 2251,
   "xPlot": 12,
   "yPlot": 18,
   "flowHeader": "Ready to Pick",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "12,18",
   "BAEendpoint": "12,18",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 13,
   "MapName": "SECAUCUS FULFILLMENT FLOW",
   "id": 2281,
   "xPlot": 4,
   "yPlot": 5,
   "flowHeader": "Ready to Pick",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "6,5",
   "BAEendpoint": "8,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "28/243",
   "description": "STABLE: Less than 0.5% of shipments in Ready to Pick status for longer than 30.0 mins."
 },
 {
   "designID": 13,
   "MapName": "SECAUCUS FULFILLMENT FLOW",
   "id": 2283,
   "xPlot": 8,
   "yPlot": 5,
   "flowHeader": "Ready to Fill",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "10,5",
   "BAEendpoint": "12,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 13,
   "MapName": "SECAUCUS FULFILLMENT FLOW",
   "id": 2284,
   "xPlot": 12,
   "yPlot": 5,
   "flowHeader": "Invoice Printed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "14,5",
   "BAEendpoint": "16,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "179/1266",
   "description": "STABLE: Less than 0.5% of shipments in Invoice Printed  status for longer than 6.0 hours."
 },
 {
   "designID": 13,
   "MapName": "SECAUCUS FULFILLMENT FLOW",
   "id": 2285,
   "xPlot": 16,
   "yPlot": 5,
   "flowHeader": "Ship Confirmed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "18,5",
   "BAEendpoint": "20,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/3",
   "description": "STABLE: Less than 0.5% of shipments in Shipment Confirmed status for longer than 2.0 days."
 },
 {
   "designID": 13,
   "MapName": "SECAUCUS FULFILLMENT FLOW",
   "id": 2286,
   "xPlot": 20,
   "yPlot": 5,
   "flowHeader": "Ship Closed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "20,5",
   "BAEendpoint": "20,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "200/1745",
   "description": "STABLE: Less than 1.0% of shipments in Shipment Closed status for longer than 24.0 hours."
 },
 {
   "designID": 6,
   "MapName": "Steve",
   "id": 41,
   "xPlot": 1,
   "yPlot": 1,
   "flowHeader": "Andrea",
   "flowURL": null,
   "seqID": 0,
   "flowStatus": "green",
   "stationType": "interchange-ysign",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "",
   "BAEendpoint": "",
   "BAEurl": "",
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 6,
   "MapName": "Steve",
   "id": 42,
   "xPlot": 2,
   "yPlot": 5,
   "flowHeader": "harold",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": null,
   "BAEmidpoint": "",
   "BAEendpoint": "",
   "BAEurl": "",
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 15,
   "MapName": "VGC FULFILLMENT FLOW",
   "id": 2293,
   "xPlot": 4,
   "yPlot": 5,
   "flowHeader": "Ready to Pick",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "6,5",
   "BAEendpoint": "8,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/1",
   "description": "STABLE: Less than 0.5% of shipments in Ready to Pick status for longer than 30.0 mins."
 },
 {
   "designID": 15,
   "MapName": "VGC FULFILLMENT FLOW",
   "id": 2294,
   "xPlot": 8,
   "yPlot": 5,
   "flowHeader": "GCR",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "10,5",
   "BAEendpoint": "12,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 15,
   "MapName": "VGC FULFILLMENT FLOW",
   "id": 2295,
   "xPlot": 12,
   "yPlot": 5,
   "flowHeader": "Ship Confirmed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "14,5",
   "BAEendpoint": "16,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 15,
   "MapName": "VGC FULFILLMENT FLOW",
   "id": 2296,
   "xPlot": 16,
   "yPlot": 5,
   "flowHeader": "Email",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "16,5",
   "BAEendpoint": "16,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "WMS FULFILLMENT FLOW",
   "id": 2223,
   "xPlot": 6,
   "yPlot": 5,
   "flowHeader": "Ready to Pick",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "yellow",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "8,5",
   "BAEendpoint": "10,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "Jul-38",
   "description": "STABLE: Less than 0.5% of shipments in Ready to Pick status for longer than 60.0 mins."
 },
 {
   "designID": 9,
   "MapName": "WMS FULFILLMENT FLOW",
   "id": 2224,
   "xPlot": 1,
   "yPlot": 1,
   "flowHeader": "",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "white",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "1,1",
   "BAEendpoint": "1,1",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": null,
   "description": null
 },
 {
   "designID": 9,
   "MapName": "WMS FULFILLMENT FLOW",
   "id": 2225,
   "xPlot": 10,
   "yPlot": 5,
   "flowHeader": "FIL to WMS",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "12,5",
   "BAEendpoint": "14,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "54/679",
   "description": "STABLE: Less than 0.5% of shipments in Forward to WMS status for longer than 20.0 mins."
 },
 {
   "designID": 9,
   "MapName": "WMS FULFILLMENT FLOW",
   "id": 2226,
   "xPlot": 14,
   "yPlot": 5,
   "flowHeader": "Acknowledged",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "16,5",
   "BAEendpoint": "18,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "980/38911",
   "description": "STABLE: Less than 0.5% of shipments in WMS Acknowledged status for longer than 2.0 days."
 },
 {
   "designID": 9,
   "MapName": "WMS FULFILLMENT FLOW",
   "id": 2227,
   "xPlot": 18,
   "yPlot": 5,
   "flowHeader": "Ship Confirmed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "20,5",
   "BAEendpoint": "22,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "0/1375",
   "description": "STABLE: Less than 0.5% of shipments in Shipment Confirmed status for longer than 20.0 mins."
 },
 {
   "designID": 9,
   "MapName": "WMS FULFILLMENT FLOW",
   "id": 2228,
   "xPlot": 22,
   "yPlot": 5,
   "flowHeader": "Ship Closed",
   "flowURL": null,
   "seqID": 1,
   "flowStatus": "green",
   "stationType": "interchange",
   "seqEND": 0,
   "lineDirection": "E",
   "textDirection": "S",
   "BAEmidpoint": "22,5",
   "BAEendpoint": "22,5",
   "BAEurl": null,
   "BAEStationType": null,
   "VAlueUnderBubble": "145851/264290",
   "description": "STABLE: Less than 1.0% of shipments in Shipment Closed status for longer than 24.0 hours."
 }
]